export const FilterSkills = [
  "API",
  "Bootstrap",
  "ChartJS",
  "Express",
  "HTML",
  "CSS",
  "MongoDB",
  "ReactJS",
  "JavaScript",
];

export const ReactList = [
  {
    id: 1,
    title: "Personal Expense Tracker",
    description:
      "During my spare time, I channeled my passion for web development by building this personal website using a combination of frontend and backend technologies",
    skills: [
      "Bootstrap",
      "ChartJS",
      "Express",
      "HTML",
      "CSS",
      "MongoDB",
      "ReactJS",
      "JavaScript",
    ],
    img: "Expense.png",
    page: "Expense",
    url: "",
    isExternal: "false",
  },
  {
    id: 2,
    title: "LeetCode Question Tracker",
    description:
      "This capstone project aims to use various machine learning models to predict the likelihood of a successful landing for SpaceX's Falcon 9 launch. ",
    skills: [
      "Bootstrap",
      "Express",
      "HTML",
      "CSS",
      "MongoDB",
      "ReactJS",
      "JavaScript",
    ],
    img: "Leetcode.png",
    page: "Leetcode",
    url: "",
    isExternal: "false",
  },
  {
    id: 3,
    title: "Weather App",
    description:
      "This capstone project aims to use various machine learning models to predict the likelihood of a successful landing for SpaceX's Falcon 9 launch. ",
    skills: [
      "API",
      "Bootstrap",
      "ChartJS",
      "HTML",
      "CSS",
      "ReactJS",
      "JavaScript",
    ],
    img: "Weather.png",
    page: "Weather",
    url: "",
    isExternal: "false",
  },
  {
    id: 4,
    title: "Stock App",
    description:
      "This capstone project aims to use various machine learning models to predict the likelihood of a successful landing for SpaceX's Falcon 9 launch. ",
    skills: [
      "API",
      "Bootstrap",
      "ChartJS",
      "HTML",
      "CSS",
      "ReactJS",
      "JavaScript",
    ],
    img: "Stock.png",
    page: "stockEarnings",
    url: "",
    isExternal: "false",
  },
];
