export const FilterSkills = [
  "API",
  "Bootstrap",
  "ChartJS",
  "Express",
  "HTML",
  "CSS",
  "MongoDB",
  "ReactJS",
  "JavaScript",
];

export const ReactList = [
  {
    id: 1,
    title: "Personal Expense Tracker",
    description:
      "During my spare time, I channeled my passion for web development by building this personal website using a combination of frontend and backend technologies",
    skills: [
      "Bootstrap",
      "ChartJS",
      "Express",
      "HTML",
      "CSS",
      "MongoDB",
      "ReactJS",
      "JavaScript",
    ],
    img: "Expense.png",
    page: "Expense",
    url: "",
    isExternal: "false",
  },
  {
    id: 2,
    title: "LeetCode Question Tracker",
    description:
      "This capstone project aims to use various machine learning models to predict the likelihood of a successful landing for SpaceX's Falcon 9 launch. ",
    skills: [
      "Bootstrap",
      "Express",
      "HTML",
      "CSS",
      "MongoDB",
      "ReactJS",
      "JavaScript",
    ],
    img: "Leetcode.png",
    page: "Leetcode",
    url: "",
    isExternal: "false",
  },
  {
    id: 3,
    title: "Weather App",
    description:
      "This capstone project aims to use various machine learning models to predict the likelihood of a successful landing for SpaceX's Falcon 9 launch. ",
    skills: [
      "API",
      "Bootstrap",
      "ChartJS",
      "HTML",
      "CSS",
      "ReactJS",
      "JavaScript",
    ],
    img: "Weather.png",
    page: "Weather",
    url: "",
    isExternal: "false",
  },
  {
    id: 4,
    title: "Stock App",
    description:
      "This capstone project aims to use various machine learning models to predict the likelihood of a successful landing for SpaceX's Falcon 9 launch. ",
    skills: [
      "API",
      "Bootstrap",
      "ChartJS",
      "HTML",
      "CSS",
      "ReactJS",
      "JavaScript",
    ],
    img: "Stock.png",
    page: "stockEarnings",
    url: "",
    isExternal: "false",
  },
  {
    id: 5,
    title: "Multiple Webviewer App",
    description:
      "The website aims to solve a problem at work where multiple websites are loaded on the same page. The website is loaded by clicking the checkbox from data tabulated on the top of the page. This enables ability to quickly load desired pages to increase job productivity. ",
    skills: ["Bootstrap", "HTML", "CSS", "ReactJS", "JavaScript"],
    img: "",
    page: "",
    url: "",
    isExternal: "true",
  },
  {
    id: 5,
    title: "RecipeBook App",
    description:
      "The website aims to solve a hungry person's inability to decide on a cuisine to make by providing multiple categories and options. By offering a diverse array of culinary inspirations, users can easily browse through a wide range of choices. This user-friendly platform will help them explore various cuisines, dishes, and recipes, each accompanied by detailed descriptions and images. Users can filter their preferences based on ingredients, cooking time, complexity, and dietary restrictions, making the decision-making process smoother.",
    skills: ["Bootstrap", "HTML", "CSS", "ReactJS", "JavaScript"],
    img: "",
    page: "",
    url: "",
    isExternal: "true",
  },
];
